# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-27 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=606, size=6),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
