# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-27 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190727_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='released',
            field=models.DateField(default=datetime.date(2019, 7, 27)),
        ),
    ]
