# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-30 18:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20190730_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='released',
            field=models.DateField(default=datetime.datetime(2019, 7, 30, 18, 10, 0, 721070, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together=set([('name', 'isbn')]),
        ),
    ]
